apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyfinder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keyfinder
  template:
    metadata:
      labels:
        app: keyfinder
    spec:
      containers:
      - name: keyfinder
        image: donghyunkang/keyfinder:latest
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "" # PUT YOUR ACCESS KEY ID HERE
        - name: AWS_SECRET_ACCESS_KEY
          value: "" # PUT YOUR SECRET ACCESS KEY HERE
        - name: AWS_REGION 
          value: "ap-northeast-2"
---
apiVersion: v1
kind: Service
metadata:
  name: keyfinder-service
  labels:
    app: keyfinder
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 32000
  selector:
    app: keyfinder
